baseURL= "https://uicard.io/blog/"
languageCode="en-us"
title = "UICardio Blog"
theme= "cactus"

[params]
  mainURL = "https://uicard.io/"
  enableSummary = true
  enableShare = true

[social]
  twitter = "https://twitter.com/uicardio"
  instagram = "https://instagram.com/uicardio"

[params.author.arvind]
  fullName = "Arvind Singh"
  email = "heyarviind@gmail.com"
  website = "https://heyarviind.com"

[params.author.haman]
  fullName = "Haman Mahal"
  email = "hamanmahal001@gmail.com"

[outputs]
  home = ["html","json","RSS"]
  page = ["html", "json","RSS"]
  section = ["html", "json","RSS"]